name: ci-real-estate-workflow
on: [push]
jobs:
  check-tets:
    runs-on: ubuntu=latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: mvn test